### ISSUE TITLE
Can't find rc file

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [EricCrosson/slack-wrap#13]
i doucle-checked with :
``` 
[ -f ${HOME}/.slack-wrap.json ] && echo "Found" || echo "Not found"
Found
```
Thanks for your help :/

**Comment by Naereen** [comment]
Can you paste the output of the error `slack-wrap` command please?

**Comment by Naereen** [comment]
Maybe also include the content of your `~/.slack-wrap.json` file and its rights? (hide the private content):
```bash
$ cat ~/.slack-wrap.json 
{
    "channel": "@lilian",
    "username": "slack-notify",
    "icon_emoji": ":ghost:",
    "webhook_url": "https://hooks.slack.com/services/XXX/XXX"
}
$ ls -larth ~/.slack-wrap.json 
-rw-rw-r-- 1 lilian lilian 190 mars   7  2017 /home/lilian/.slack-wrap.json
```

Note that you have to create the hook in your slack team!

**Comment by ThibaultGROUEIX** [comment]
```
slack-wrap "echo $PATH"
could not find rc file
cat ~/.slack-wrap.json
{
    "channel": "@tibogroux",
    "username": "slack-notify",
    "webhook_url": "https://hooks.slack.com/services/x/x/x"
}
ls -larth ~/.slack-wrap.json 
-rw-rw-r-- 1 thibault thibault 164 nov.  20 19:02 /home/thibault/.slack-wrap.json

```

**Comment by Naereen** [comment]
Then I'm puzzled, I don't know more.
@EricCrosson could you help?

**Comment by EricCrosson** [comment]
This issue can arise depending on how you installed (where you installed) slack-wrap. The conf-finding function is not very sophisticated at this early version

This issue may shed some light 
https://github.com/EricCrosson/slack-wrap/issues/1

**Comment by EricCrosson** [comment]
https://github.com/EricCrosson/slack-wrap/blob/master/slack-wrap.js#L15

The function basically looks in directories above where the source is stored. See if that setup locates your settings

**Comment by ThibaultGROUEIX** [comment]
#1 helped ! ```sudo ln -s /home/thibault/.slack-wrap.json /usr/local/lib/node_modules/slack-wrap/.slack-wrap.json```solved it. Thanks @Naereen @EricCrosson

**Comment by Naereen** [comment]
OK, I see. I didn't encounter the issue as I installed slack-wrap locally with npm (so in `~/.node_modules`).
(Closing?)

**Comment by EricCrosson** [comment]
Awesome, glad you got a workaround!
